<a href="https://colab.research.google.com/github/zunish629-bit/python-task/blob/main/practice_tasks_(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Name : Zunaira Sheikh
# Roll no. :868278

In [ ]:
#task pandas 1
#create This Student DataFrame:
import pandas as pd
data = {   "name":["Ali","sara","Ahmed" ,"Ayesha ","Zain"],
            "Mark":[70,85,60,95,45]
}
df = pd.DataFrame(data)
df

      name  Mark
0      Ali    70
1     sara    85
2    Ahmed    60
3  Ayesha     95
4     Zain    45

In [ ]:
#- Average marks
print(df["Mark"].mean())
#Maximum marks
print(df["Mark"].max())
#Minimum marks
print(df["Mark"].min())
#Total students
print(df["name"].count())

71.0
95
45
5

In [ ]:
from numpy import less
#task 2
df
print("--------Greater Mark-----------")
greater =df[df["Mark"]>50]
print(greater)
print("---------Less Mark----------")
#less mark
less=df[df["Mark"]<50]
print(less)

--------Greater Mark-----------
      name  Mark
0      Ali    70
1     sara    85
2    Ahmed    60
3  Ayesha     95
---------Less Mark----------
   name  Mark
4  Zain    45

In [ ]:
#task 3
df["city"]=["karachi","lahore","islamabad","kashmir","hyderabad"]
df[df["city"]=="karachi"]

  name  Mark     city
0  Ali    70  karachi

In [ ]:
import pandas as pd
#task 4
data={
      "name":["zunaira","ali","musfira","nimra","saad"],
    "cousre":["AI","WEB","AI","WEB","AI"],
    "mark":[76,86,65,65,87]
    }

df=pd.DataFrame(data)
df

      name cousre  mark
0  zunaira     AI    76
1      ali    WEB    86
2  musfira     AI    65
3    nimra    WEB    65
4     saad     AI    87

In [ ]:
result=df.groupby("cousre")["mark"].mean()
result

cousre
AI     76.0
WEB    75.5
Name: mark, dtype: float64

In [ ]:
#task pandas 5

import pandas as pd
data = {   "name":["Ali","sara","Ahmed" ,"Ayesha ","Zain"],
            "Marks":[70,'null',60,95,'null'],
           "age":[20,20,"null",19,18],

}
df = pd.DataFrame(data)
df

      name Marks   age
0      Ali    70    20
1     sara  null    20
2    Ahmed    60  null
3  Ayesha     95    19
4     Zain  null    18

In [ ]:
print(df.isnull().sum())

name     0
Marks    0
age      0
dtype: int64

In [ ]:
import numpy as np

df['Marks'] = pd.to_numeric(df['Marks'], errors='coerce')
df['age'] = pd.to_numeric(df['age'], errors='coerce')


df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df['age'] = df['age'].fillna(df['age'].mean())


df

      name  Marks    age
0      Ali   70.0  20.00
1     sara   75.0  20.00
2    Ahmed   60.0  19.25
3  Ayesha    95.0  19.00
4     Zain   75.0  18.00